### ISSUE TITLE
vendor/ folder

### ISSUE THREAD

**Issue by fortytw2** [uniplaces/carbon#25]
(accidentally hit enter before I meant to, my bad)

It's generally not good practice to vendor dependencies inside a library, Go itself doesn't really support nested `vendor/` folders, and so anyone then vendoring carbon will either flatten, or remove the nested folder here :)

**Comment by mlimaloureiro** [comment]
you're right for @fortytw2, @hfcorreia have a look, feel free to open a pr if you want @fortytw2, thanks!

**Comment by hfcorreia** [comment]
Fixed in #26
