### ISSUE TITLE
AddMonths Bug? 

### ISSUE THREAD

**Issue by BigKuCha** [uniplaces/carbon#41]
```
e := carbon.Now().EndOfMonth()
fmt.Println(e)
fmt.Println(e.Copy().AddMonths(-1))
```

When I run the above code， I got the result:

```
2018-05-31 23:59:59
2018-05-01 23:59:59
```
I expect the second value is `2018-04-30 23:59:59`
is this a bug? 

package version:
name: github.com/uniplaces/carbon
version: 2ed00d8a452957d017135066f4e9bda33821d426

**Comment by hfcorreia** [comment]
This is the expected behaviour. If you subtract a month there is no 31 of April. So the behaviour is to overflow to the next day, which is 2018-05-01.

Check in PHP:
```
require 'Carbon/Carbon.php';
use Carbon\Carbon;

$now = Carbon::create(2018, 5, 31, 23, 59, 59, 'GMT');
$now->addMonths(-1);
echo $now;
```

The previous code will return: `2018-05-01 23:59:59`

Sorry for the late response
