### ISSUE TITLE
SubMonths error

### ISSUE THREAD

**Issue by JeffreyBool** [uniplaces/carbon#55]
carbon.Now().SubMonths(1).Format(model.YEAR_MONTH_FORMAT)

The result is ： 201907

Should be： 201906

**Comment by alister** [comment]
What is the value of `model.YEAR_MONTH_FORMAT`, and if you replace `.Now()` with other (fixed) dates, do they all work, fail, or a mix?

**Comment by gouguoyin** [comment]
carbon.Parse("2020-02-29 13:14:15").SubMonths(3).ToDateTimeString() // 2019-11-29 13:14:15
you can try [go-carbon](https://github.com/golang-module/carbon)
