### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by duolabmeng6** [uniplaces/carbon#57]
gotTime, err := Now().SubMinute().DiffForHumans(nil, false, false, false)

**Comment by FileGo** [comment]
@duolabmeng6 Could you please clarify on that or provide an example? [This code](https://play.golang.org/p/3flrlqKgo9m) runs fine both on Playground and locally.

**Comment by mops1k** [comment]
This issue reprodeces if you using library as go module

**Comment by rntdrts** [comment]
Fixed on 0.2.0.
