### ISSUE TITLE
Error in DiffInMonths function

### ISSUE THREAD

**Issue by fstiffo** [uniplaces/carbon#69]
Using github.com/uniplaces/carbon v0.1.6, the following code:

```	
d1, _ := carbon.Create(2019, 07, 1, 0, 0, 0, 0, time.UTC.String())
d2, _ := carbon.Create(2021, 07, 24, 0, 0, 0, 0, time.UTC.String())
fmt.Println(d2.DiffInMonths(d1, true))
```

prints 48 not 24.

Curiosly, the code:

```	
d1, _ := carbon.Create(2019, 07, 1, 0, 0, 0, 0, time.UTC.String())
d2, _ := carbon.Create(2020, 07, 24, 0, 0, 0, 0, time.UTC.String())
fmt.Println(d2.DiffInMonths(d1, true))
```

prints 12 the correct value. Maybe a problem with leap years?

**Comment by gouguoyin** [comment]
you can try [carbon](https://github.com/golang-module/carbon)，a simple, semantic and developer-friendly golang package for datetime. its result is 24
![image](https://user-images.githubusercontent.com/13517412/127761141-a4021ee5-55ad-43c0-bfa4-1641b87625b7.png)

**Comment by rntdrts** [comment]
Probably a bit to late, but is fixed on the new version. You can check it [here](https://go.dev/play/p/U-dN1VE1Na_c):
